// AUTO-GENERATED — do not edit by hand.
// Device label -> product image path (under /public), extracted from
// the sell-funnel catalog in app/page.tsx.
// Regenerate: node scripts/gen-device-images.mjs

export const DEVICE_IMAGES: Record<string, string> = {
  "Aegis R": "/devices/msi-aegis.webp",
  "Aegis R2": "/devices/msi-aegis.webp",
  "Aegis RS": "/devices/msi-aegis.webp",
  "Aegis RS2": "/devices/msi-aegis.webp",
  "Aegis SE": "/devices/msi-aegis.webp",
  "Aegis Ti5": "/devices/msi-aegis.webp",
  "Aegis ZS": "/devices/msi-aegis.webp",
  "Aegis ZS2": "/devices/msi-aegis.webp",
  "Alienware 13": "/devices/alienware-13-r3.webp",
  "Alienware 13 R2": "/devices/alienware-13-r2.webp",
  "Alienware 13 R3": "/devices/alienware-13-r3.webp",
  "Alienware 15": "/devices/alienware-15-r4.webp",
  "Alienware 15 R2": "/devices/alienware-15-r2.webp",
  "Alienware 15 R3": "/devices/alienware-15-r3.webp",
  "Alienware 15 R4": "/devices/alienware-15-r4.webp",
  "Alienware 16 Area-51 (2026)": "/devices/alienware-16-area-51.webp",
  "Alienware 16 Aurora (2026)": "/devices/alienware-16-aurora.webp",
  "Alienware 16X Aurora (2026)": "/devices/alienware-16x-aurora.webp",
  "Alienware 17": "/devices/alienware-17-r5.webp",
  "Alienware 17 R2": "/devices/alienware-17-r2.webp",
  "Alienware 17 R3": "/devices/alienware-17-r3.webp",
  "Alienware 17 R4": "/devices/alienware-17-r4.webp",
  "Alienware 17 R5": "/devices/alienware-17-r5.webp",
  "Alienware 18 Area-51 (2026)": "/devices/alienware-18-area-51.webp",
  "Alienware Area-51m R1": "/devices/alienware-area-51m.webp",
  "Alienware Area-51m R2": "/devices/alienware-area-51m.webp",
  "Alienware m15 R5 (Ryzen)": "/devices/alienware-m15.webp",
  "Alienware m15 R6": "/devices/alienware-m15.webp",
  "Alienware m15 R7": "/devices/alienware-m15.webp",
  "Alienware m16 R1": "/devices/alienware-m16.webp",
  "Alienware m16 R2": "/devices/alienware-m16.webp",
  "Alienware m17 R5 (AMD flagship)": "/devices/alienware-m17.webp",
  "Alienware m18 R1": "/devices/alienware-m18.webp",
  "Alienware m18 R2": "/devices/alienware-m18.webp",
  "Alienware x14 R1": "/devices/alienware-x14.webp",
  "Alienware x14 R2": "/devices/alienware-x14.webp",
  "Alienware x15 R1": "/devices/alienware-x15.webp",
  "Alienware x15 R2": "/devices/alienware-x15.webp",
  "Alienware x16 R1": "/devices/alienware-x16.webp",
  "Alienware x16 R2": "/devices/alienware-x16.webp",
  "Alienware x17 R1": "/devices/alienware-x17.webp",
  "Alienware x17 R2": "/devices/alienware-x17.webp",
  "Apple Vision Pro (M2, 2024)": "/devices/apple-vision-pro.png",
  "Apple Vision Pro (M5, 2025)": "/devices/apple-vision-pro.png",
  "Apple Watch SE (1st Gen)": "/devices/apple-watch-se-1.webp",
  "Apple Watch SE (2nd Gen)": "/devices/apple-watch-se-2.webp",
  "Apple Watch Series 10": "/devices/apple-watch-series-10.webp",
  "Apple Watch Series 7": "/devices/apple-watch-series-7.webp",
  "Apple Watch Series 8": "/devices/apple-watch-series-8.webp",
  "Apple Watch Series 9": "/devices/apple-watch-series-9.webp",
  "Apple Watch Ultra": "/devices/apple-watch-ultra.webp",
  "Apple Watch Ultra 2": "/devices/apple-watch-ultra-2.webp",
  "Apple Watch Ultra 3": "/devices/apple-watch-ultra-3.webp",
  "Approach S42": "/devices/pixel-watch.png",
  "Approach S44": "/devices/pixel-watch.png",
  "Approach S50": "/devices/pixel-watch.png",
  "Approach S62": "/devices/pixel-watch.png",
  "Approach S70": "/devices/pixel-watch.png",
  "Area Series": "/devices/alienware-18-area-51.webp",
  "Area-51 Desktop": "/devices/alienware-area-51-desktop.webp",
  "Aurora Laptop": "/devices/alienware-16x-aurora.webp",
  "Aurora R10": "/devices/alienware-aurora-r10.webp",
  "Aurora R12": "/devices/alienware-aurora-r12.webp",
  "Aurora R13": "/devices/alienware-aurora-r13.webp",
  "Aurora R14": "/devices/alienware-aurora-r14.webp",
  "Aurora R15": "/devices/alienware-aurora-r15.webp",
  "Aurora R16": "/devices/alienware-aurora-r16.webp",
  "Codex R": "/devices/msi-codex.webp",
  "Codex R2": "/devices/msi-codex.webp",
  "Codex Z": "/devices/msi-codex.webp",
  "Dell Pro": "/devices/dell-xps.webp",
  "Dell Pro 13": "/devices/dell-xps.webp",
  "Dell Pro 13 Plus (2-in-1) PB13250": "/devices/d_pro_13_plus_2in1_pb13250.png",
  "Dell Pro 13 Plus (2-in-1) PB13255": "/devices/d_pro_13_plus_2in1_pb13255.png",
  "Dell Pro 13 Plus PB13250": "/devices/d_pro_13_plus_pb13250.png",
  "Dell Pro 13 Plus PB13255": "/devices/d_pro_13_plus_pb13255.png",
  "Dell Pro 13 Premium PA13250": "/devices/d_pro_13_premium_pa13250.png",
  "Dell Pro 14": "/devices/dell-xps.webp",
  "Dell Pro 14 Essential PV14250": "/devices/d_pro_14_essential_pv14250.png",
  "Dell Pro 14 Essential PV14255": "/devices/d_pro_14_essential_pv14255.png",
  "Dell Pro 14 PC14250": "/devices/d_pro_14_pc14250.png",
  "Dell Pro 14 PC14255": "/devices/d_pro_14_pc14255.png",
  "Dell Pro 14 Plus (2-in-1) PB14250": "/devices/d_pro_14_plus_2in1_pb14250.png",
  "Dell Pro 14 Plus (2-in-1) PB14255": "/devices/d_pro_14_plus_2in1_pb14255.png",
  "Dell Pro 14 Plus PB14250": "/devices/d_pro_14_plus_pb14250.png",
  "Dell Pro 14 Plus PB14255": "/devices/d_pro_14_plus_pb14255.png",
  "Dell Pro 14 Premium PA14250": "/devices/d_pro_14_premium_pa14250.png",
  "Dell Pro 16": "/devices/dell-xps.webp",
  "Dell Pro 16 PC16250": "/devices/d_pro_16_pc16250.png",
  "Dell Pro 16 PC16255": "/devices/d_pro_16_pc16255.png",
  "Dell Pro 16 Plus PB16250": "/devices/d_pro_16_plus_pb16250.png",
  "Dell Pro 16 Plus PB16255": "/devices/d_pro_16_plus_pb16255.png",
  "Dell Pro Max 14 MC14250": "/devices/d_pro_max_14_mc14250.png",
  "Dell Pro Max 14 MC14255": "/devices/d_pro_max_14_mc14255.png",
  "Dell Pro Max 14 Premium MA14250": "/devices/d_pro_max_14_premium_ma14250.png",
  "Dell Pro Max 16 MC16250": "/devices/d_pro_max_16_mc16250.png",
  "Dell Pro Max 16 MC16255": "/devices/d_pro_max_16_mc16255.png",
  "Dell Pro Max 16 Plus MB16250": "/devices/d_pro_max_16_plus_mb16250.png",
  "Dell Pro Max 16 Premium MA16250": "/devices/d_pro_max_16_premium_ma16250.png",
  "Descent G1": "/devices/pixel-watch.png",
  "Descent G2": "/devices/pixel-watch.png",
  "Descent Mk1": "/devices/pixel-watch.png",
  "Descent Mk2": "/devices/pixel-watch.png",
  "Descent Mk3": "/devices/pixel-watch.png",
  "DJI Air 2S": "/devices/dji_air_2s.png",
  "DJI Air 3": "/devices/dji_air_3.png",
  "DJI Air 3S": "/devices/dji_air_3s.png",
  "DJI Avata": "/devices/dji_avata.png",
  "DJI Avata 2": "/devices/dji_avata_2.png",
  "DJI Flip": "/devices/dji_flip.png",
  "DJI FPV": "/devices/dji_fpv.png",
  "DJI Inspire 1": "/devices/dji_inspire_2.png",
  "DJI Inspire 2": "/devices/dji_inspire_2.png",
  "DJI Mavic 2 Pro": "/devices/dji_mavic_2_pro.png",
  "DJI Mavic 2 Zoom": "/devices/dji_mavic_2_zoom.png",
  "DJI Mavic 3": "/devices/dji_mavic_3.png",
  "DJI Mavic 3 Cine": "/devices/dji_mavic_3_cine.png",
  "DJI Mavic 3 Classic": "/devices/dji_mavic_3_classic.png",
  "DJI Mavic 3 Pro": "/devices/dji_mavic_3_pro.png",
  "DJI Mavic 3 Pro Cine": "/devices/dji_mavic_3_pro.png",
  "DJI Mavic 4 Pro": "/devices/dji_mavic_4_pro.png",
  "DJI Mavic Air 2": "/devices/dji_mavic_air_2.png",
  "DJI Mavic Mini": "/devices/dji_mavic_mini.png",
  "DJI Mavic Pro": "/devices/dji_mavic_pro.png",
  "DJI Mavic Pro Platinum": "/devices/dji_mavic_pro_platinum.png",
  "DJI Mini 2": "/devices/dji_mini_3.png",
  "DJI Mini 2 SE": "/devices/dji_mini_2_se.png",
  "DJI Mini 3": "/devices/dji_mini_3.png",
  "DJI Mini 3 Pro": "/devices/dji_mini_3_pro.png",
  "DJI Mini 4 Pro": "/devices/dji_mini_4_pro.png",
  "DJI Mini SE": "/devices/dji_mini_se.png",
  "DJI Phantom 3 Advanced": "/devices/dji_phantom_3.png",
  "DJI Phantom 3 Pro": "/devices/dji_phantom_3.png",
  "DJI Phantom 3 Standard": "/devices/dji_phantom_3.png",
  "DJI Phantom 4": "/devices/dji_phantom_4.png",
  "DJI Phantom 4 Advanced": "/devices/dji_phantom_4.png",
  "DJI Phantom 4 Pro": "/devices/dji_phantom_4_pro.png",
  "DJI Phantom 4 Pro v2": "/devices/dji_phantom_4_pro.png",
  "DJI Spark": "/devices/dji_spark.png",
  "EliteBook": "/devices/hp-elitebook-eb_std-hp-elitebook-g1a.png",
  "EliteBook G10": "/devices/hp-elitebook-eb_std-hp-elitebook-g10.png",
  "EliteBook G11": "/devices/hp-elitebook-eb_std-hp-elitebook-g11.png",
  "EliteBook G1a": "/devices/hp-elitebook-eb_std-hp-elitebook-g1a.png",
  "EliteBook G1i": "/devices/hp-elitebook-eb_std-hp-elitebook-g1i.png",
  "EliteBook G1q": "/devices/hp-elitebook-eb_std-hp-elitebook-g1q.png",
  "EliteBook G4": "/devices/hp-elitebook-eb_std-hp-elitebook-g4.png",
  "EliteBook G5": "/devices/hp-elitebook-eb_std-hp-elitebook-g5.png",
  "EliteBook G6": "/devices/hp-elitebook-eb_std-hp-elitebook-g6.png",
  "EliteBook G7": "/devices/hp-elitebook-eb_std-hp-elitebook-g7.png",
  "EliteBook G8": "/devices/hp-elitebook-eb_std-hp-elitebook-g8.png",
  "EliteBook G9": "/devices/hp-elitebook-eb_std-hp-elitebook-g9.png",
  "EliteBook Ultra": "/devices/hp-elitebook-eb_ultra-hp-elitebook-ultra-g1q.png",
  "EliteBook Ultra G1i": "/devices/hp-elitebook-eb_ultra-hp-elitebook-ultra-g1i.png",
  "EliteBook Ultra G1q": "/devices/hp-elitebook-eb_ultra-hp-elitebook-ultra-g1q.png",
  "EliteDesk 800 G9": "/devices/hp-elitedesk-800.webp",
  "Enduro": "/devices/pixel-watch.png",
  "Enduro 2": "/devices/pixel-watch.png",
  "Enduro 3": "/devices/pixel-watch.png",
  "Envy": "/devices/hp-envy-hp-envy-x360.png",
  "Envy 13": "/devices/hp-envy-hp-envy-13.png",
  "Envy 15": "/devices/hp-envy-hp-envy-15.png",
  "Envy 17": "/devices/hp-envy-hp-envy-17.png",
  "Envy 34 All-in-One": "/devices/lenovo-ideacentre.webp",
  "Envy x360": "/devices/hp-envy-hp-envy-x360.png",
  "Epix Gen 2": "/devices/pixel-watch.png",
  "Epix Pro Gen 2": "/devices/pixel-watch.png",
  "ExpertBook": "/devices/asus-expertbook-expertbook-b9.png",
  "ExpertBook B2": "/devices/asus-expertbook-expertbook-b2.png",
  "ExpertBook B3": "/devices/asus-expertbook-expertbook-b3.png",
  "ExpertBook B5": "/devices/asus-expertbook-expertbook-b5.png",
  "ExpertBook B9": "/devices/asus-expertbook-expertbook-b9.png",
  "ExpertBook P1": "/devices/asus-expertbook-expertbook-p1.png",
  "ExpertBook P5": "/devices/asus-expertbook-expertbook-p5.png",
  "ExpertCenter D5": "/devices/asus-rog-desktop.webp",
  "Fenix 7": "/devices/pixel-watch.png",
  "Fenix 7S": "/devices/pixel-watch.png",
  "Fenix 7X": "/devices/pixel-watch.png",
  "Fenix 8 AMOLED": "/devices/pixel-watch.png",
  "Fenix 8 Pro": "/devices/pixel-watch.png",
  "Fenix 8 Solar": "/devices/pixel-watch.png",
  "Fenix E": "/devices/pixel-watch.png",
  "Fold Series": "/pixel-fold-series.webp",
  "Forerunner 165": "/devices/pixel-watch.png",
  "Forerunner 165 Music": "/devices/pixel-watch.png",
  "Forerunner 245": "/devices/pixel-watch.png",
  "Forerunner 245 Music": "/devices/pixel-watch.png",
  "Forerunner 255": "/devices/pixel-watch.png",
  "Forerunner 255 Music": "/devices/pixel-watch.png",
  "Forerunner 255S": "/devices/pixel-watch.png",
  "Forerunner 255S Music": "/devices/pixel-watch.png",
  "Forerunner 265": "/devices/pixel-watch.png",
  "Forerunner 265S": "/devices/pixel-watch.png",
  "Forerunner 570": "/devices/pixel-watch.png",
  "Forerunner 745": "/devices/pixel-watch.png",
  "Forerunner 945": "/devices/pixel-watch.png",
  "Forerunner 945 LTE": "/devices/pixel-watch.png",
  "Forerunner 955": "/devices/pixel-watch.png",
  "Forerunner 955 Solar": "/devices/pixel-watch.png",
  "Forerunner 965": "/devices/pixel-watch.png",
  "Forerunner 970": "/devices/pixel-watch.png",
  "G Series": "/devices/dell-xps.webp",
  "G15": "/devices/dell-xps.webp",
  "G15 5510": "/devices/d_g15_5510.png",
  "G15 5511": "/devices/d_g15_5511.png",
  "G15 5515": "/devices/d_g15_5515.png",
  "G15 5520": "/devices/d_g15_5520.png",
  "G15 5521": "/devices/d_g15_5521.png",
  "G15 5525": "/devices/d_g15_5525.png",
  "G15 5530": "/devices/d_g15_5530.png",
  "G15 5535": "/devices/d_g15_5535.png",
  "G16": "/devices/dell-xps.webp",
  "G16 7620": "/devices/d_g16_7620.png",
  "G16 7630": "/devices/d_g16_7630.png",
  "G3": "/devices/dell-xps.webp",
  "G3 3500": "/devices/dell-g_series-g3-3500.png",
  "G3 3579": "/devices/dell-g_series-g3-3579.png",
  "G3 3590": "/devices/dell-g_series-g3-3590.png",
  "G3 3779": "/devices/dell-g_series-g3-3779.png",
  "G5": "/devices/dell-xps.webp",
  "G5 5500": "/devices/dell-g_series-g5-5500.png",
  "G5 5505 SE": "/devices/dell-g_series-g5-5505-se.png",
  "G5 5587": "/devices/dell-g_series-g5-5587.png",
  "G5 5590": "/devices/dell-g_series-g5-5590.png",
  "G7": "/devices/dell-xps.webp",
  "G7 7500": "/devices/dell-g_series-g7-7500.png",
  "G7 7588": "/devices/dell-g_series-g7-7588.png",
  "G7 7590": "/devices/dell-g_series-g7-7590.png",
  "G7 7700": "/devices/d_g7_7700.png",
  "G7 7790": "/devices/d_g7_7790.png",
  "Galaxy Book": "/devices/sgbk_1.png",
  "Galaxy Book 2": "/devices/sgbk_2_pro.png",
  "Galaxy Book 3": "/devices/sgbk_3_ultra.png",
  "Galaxy Book 4": "/devices/sgbk_4_ultra.png",
  "Galaxy Book 5": "/devices/sgbk_5_pro.png",
  "Galaxy Book Flex": "/devices/sgbk_1_flex.png",
  "Galaxy Book Flex Alpha": "/devices/sgbk_1_flex_alpha.png",
  "Galaxy Book Flex2 Alpha": "/devices/sgbk_1_flex2_alpha.png",
  "Galaxy Book Ion": "/devices/sgbk_1_ion.png",
  "Galaxy Book Odyssey": "/devices/sgbk_1_odyssey.png",
  "Galaxy Book Pro": "/devices/sgbk_1_pro.png",
  "Galaxy Book Pro 360": "/devices/sgbk_1_pro_360.png",
  "Galaxy Book2": "/devices/sgbk_2.png",
  "Galaxy Book2 360": "/devices/sgbk_2_360.png",
  "Galaxy Book2 Pro": "/devices/sgbk_2_pro.png",
  "Galaxy Book2 Pro 360": "/devices/sgbk_2_pro_360.png",
  "Galaxy Book3": "/devices/sgbk_3.png",
  "Galaxy Book3 360": "/devices/sgbk_3_360.png",
  "Galaxy Book3 Pro": "/devices/sgbk_3_pro.png",
  "Galaxy Book3 Pro 360": "/devices/sgbk_3_pro_360.png",
  "Galaxy Book3 Ultra": "/devices/sgbk_3_ultra.png",
  "Galaxy Book4": "/devices/sgbk_4.png",
  "Galaxy Book4 360": "/devices/sgbk_4_360.png",
  "Galaxy Book4 Edge": "/devices/sgbk_4_edge.png",
  "Galaxy Book4 Pro": "/devices/sgbk_4_pro.png",
  "Galaxy Book4 Pro 360": "/devices/sgbk_4_pro_360.png",
  "Galaxy Book4 Ultra": "/devices/sgbk_4_ultra.png",
  "Galaxy Book5": "/devices/sgbk_5.png",
  "Galaxy Book5 360": "/devices/sgbk_5_360.png",
  "Galaxy Book5 Pro": "/devices/sgbk_5_pro.png",
  "Galaxy Book5 Pro 360": "/devices/sgbk_5_pro_360.png",
  "Galaxy Note 10": "/devices/gnote10.webp",
  "Galaxy Note 10+": "/devices/gnote10p.webp",
  "Galaxy Note 10+ 5G": "/devices/gnote10p5g.webp",
  "Galaxy Note 20 5G": "/devices/gnote20.webp",
  "Galaxy Note 20 Ultra 5G": "/devices/gnote20u.webp",
  "Galaxy Note 9": "/devices/gnote9.webp",
  "Galaxy S20": "/devices/gs20.webp",
  "Galaxy S20 FE": "/devices/gs20fe.webp",
  "Galaxy S20 Ultra": "/devices/gs20u.webp",
  "Galaxy S20+": "/devices/gs20p.webp",
  "Galaxy S21": "/devices/gs21.webp",
  "Galaxy S21 FE": "/devices/gs21fe.webp",
  "Galaxy S21 Ultra": "/devices/gs21u.webp",
  "Galaxy S21+": "/devices/gs21p.webp",
  "Galaxy S22": "/devices/gs22.webp",
  "Galaxy S22 Ultra": "/devices/gs22u.webp",
  "Galaxy S22+": "/devices/gs22p.webp",
  "Galaxy S23": "/devices/gs23.webp",
  "Galaxy S23 FE": "/devices/gs23fe.webp",
  "Galaxy S23 Ultra": "/devices/gs23u.webp",
  "Galaxy S23+": "/devices/gs23p.webp",
  "Galaxy S24": "/devices/gs24.webp",
  "Galaxy S24 FE": "/devices/gs24fe.webp",
  "Galaxy S24 Ultra": "/devices/gs24u.webp",
  "Galaxy S24+": "/devices/gs24p.webp",
  "Galaxy S25": "/devices/gs25.webp",
  "Galaxy S25 Edge": "/devices/gs25edge.webp",
  "Galaxy S25 FE": "/devices/gs25fe.webp",
  "Galaxy S25 Ultra": "/devices/gs25u.webp",
  "Galaxy S25+": "/devices/gs25p.webp",
  "Galaxy S26": "/devices/gs26.webp",
  "Galaxy S26 Ultra": "/devices/gs26u.webp",
  "Galaxy S26+": "/devices/gs26p.webp",
  "Galaxy Tab A9+": "/devices/galaxy-tab-a9-plus.webp",
  "Galaxy Tab S10 FE": "/devices/galaxy-tab-s10-fe.webp",
  "Galaxy Tab S10 FE+": "/devices/galaxy-tab-s10-fe-plus.webp",
  "Galaxy Tab S10 Lite": "/devices/galaxy-tab-s10-lite.webp",
  "Galaxy Tab S10 Ultra": "/devices/galaxy-tab-s10-ultra.png",
  "Galaxy Tab S10+": "/devices/galaxy-tab-s10-plus.webp",
  "Galaxy Tab S11": "/devices/galaxy-tab-s11.webp",
  "Galaxy Tab S11 Ultra": "/devices/galaxy-tab-s11-ultra.webp",
  "Galaxy Tab S4 10.5": "/devices/galaxy-tab-s4-105.webp",
  "Galaxy Tab S5e": "/devices/galaxy-tab-s5e.webp",
  "Galaxy Tab S6": "/devices/galaxy-tab-s6.webp",
  "Galaxy Tab S6 Lite": "/devices/galaxy-tab-s6-lite.webp",
  "Galaxy Tab S7": "/devices/galaxy-tab-s7.webp",
  "Galaxy Tab S7 FE": "/devices/galaxy-tab-s7-fe.png",
  "Galaxy Tab S7+": "/devices/galaxy-tab-s7-plus.webp",
  "Galaxy Tab S8": "/devices/galaxy-tab-s8.webp",
  "Galaxy Tab S8 Ultra": "/devices/galaxy-tab-s8-ultra.webp",
  "Galaxy Tab S8+": "/devices/galaxy-tab-s8-plus.webp",
  "Galaxy Tab S9": "/devices/galaxy-tab-s9.webp",
  "Galaxy Tab S9 FE": "/devices/galaxy-tab-s9-fe.webp",
  "Galaxy Tab S9 FE+": "/devices/galaxy-tab-s9-fe-plus.webp",
  "Galaxy Tab S9 Ultra": "/devices/galaxy-tab-s9-ultra.webp",
  "Galaxy Tab S9+": "/devices/galaxy-tab-s9-plus.webp",
  "Galaxy Watch 7": "/devices/samsung-watch-7.webp",
  "Galaxy Watch 8": "/devices/samsung-watch-7.webp",
  "Galaxy Watch 8 Classic": "/devices/samsung-watch-7.webp",
  "Galaxy Watch Ultra": "/devices/samsung-watch-7.webp",
  "Galaxy Watch Ultra (2025)": "/devices/samsung-watch-7.webp",
  "Galaxy Z Flip 3": "/devices/gzflip3.webp",
  "Galaxy Z Flip 4": "/devices/gzflip4.webp",
  "Galaxy Z Flip 5": "/devices/gzflip5.webp",
  "Galaxy Z Flip 6": "/devices/gzflip6.webp",
  "Galaxy Z Flip 7": "/devices/gzflip7.webp",
  "Galaxy Z Fold 3": "/devices/gzfold3.webp",
  "Galaxy Z Fold 4": "/devices/gzfold4.webp",
  "Galaxy Z Fold 5": "/devices/gzfold5.webp",
  "Galaxy Z Fold 6": "/devices/gzfold6.webp",
  "Galaxy Z Fold 7": "/devices/gzfold7.webp",
  "Galaxy Z TriFold": "/devices/gztrifold.webp",
  "Gram": "/devices/lg_gr16_24.png",
  "Gram 14": "/devices/lg_gr14_24.png",
  "Gram 14 (2-in-1)": "/devices/lg_gr14t_24.png",
  "Gram 15": "/devices/lg_gr15_23.png",
  "Gram 16": "/devices/lg_gr16_24.png",
  "Gram 16 (2-in-1)": "/devices/lg_gr16t_24.png",
  "Gram 17": "/devices/lg_gr17_24.png",
  "Gram Pro": "/devices/lg_grpro16_25.png",
  "Gram Pro 16": "/devices/lg_grpro16_25.png",
  "Gram Pro 16 (2-in-1)": "/devices/lg_grpro16t_24.png",
  "Gram Pro 17": "/devices/lg_grpro17_25.png",
  "Gram SuperSlim": "/devices/lg_grultra15.png",
  "Gram SuperSlim 15": "/devices/lg_grultra15.png",
  "IdeaCentre 5i": "/devices/lenovo-thinkcentre-sff.webp",
  "IdeaPad": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad 3": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad 330s": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad 3i": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad 5": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad 5i 2-in-1": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad Flex 5": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad Flex 5i": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad Gaming 3": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad Gaming 3i": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad L340": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad S340": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad S540": "/devices/lenovo-laptop-generic.svg",
  "IdeaPad Slim 7": "/devices/lenovo-laptop-generic.svg",
  "iMac 24\" M1": "/devices/imac-24-m1.webp",
  "iMac 24\" M3": "/devices/imac-24-m3.webp",
  "iMac 24\" M4": "/devices/imac-24-m4.webp",
  "Inspiron": "/devices/dell-inspiron-15.webp",
  "Inspiron 14": "/devices/dell-inspiron-15.webp",
  "Inspiron 15": "/devices/dell-inspiron-15.webp",
  "Inspiron 16 Plus": "/devices/dell-inspiron-15.webp",
  "Inspiron 3000": "/devices/dell-inspiron-15.webp",
  "Inspiron 3400 Series": "/devices/dell-inspiron-inspiron_3000-3000_inspiron-3000-14.png",
  "Inspiron 3500 Series": "/devices/dell-inspiron-inspiron_3000-3000_inspiron-3000-15.png",
  "Inspiron 3700 Series": "/devices/dell-inspiron-inspiron_3000-3000_inspiron-3000-17.png",
  "Inspiron 5000": "/devices/dell-inspiron-15.webp",
  "Inspiron 5300 Series": "/devices/dell-inspiron-inspiron_5000-5000_inspiron-5000-13.png",
  "Inspiron 5400 Series": "/devices/dell-inspiron-inspiron_5000-5000_inspiron-5000-14.png",
  "Inspiron 5500 Series": "/devices/dell-inspiron-inspiron_5000-5000_inspiron-5000-15.png",
  "Inspiron 5600 Series": "/devices/dell-inspiron-inspiron_5000-5000_inspiron-5000-16.png",
  "Inspiron 5700 Series": "/devices/dell-inspiron-inspiron_5000-5000_inspiron-5000-17.png",
  "Inspiron 7000": "/devices/dell-inspiron-15.webp",
  "Inspiron 7300 Series": "/devices/dell-inspiron-inspiron_7000-7000_inspiron-7000-13.png",
  "Inspiron 7400 Series": "/devices/dell-inspiron-inspiron_7000-7000_inspiron-7000-14.png",
  "Inspiron 7500 Series": "/devices/dell-inspiron-inspiron_7000-7000_inspiron-7000-15.png",
  "Inspiron 7600 Series": "/devices/dell-inspiron-inspiron_7000-7000_inspiron-7000-16.png",
  "Inspiron 7700 Series": "/devices/dell-inspiron-inspiron_7000-7000_inspiron-7000-17.png",
  "Instinct 2": "/devices/pixel-watch.png",
  "Instinct 2S": "/devices/pixel-watch.png",
  "Instinct 2X": "/devices/pixel-watch.png",
  "Instinct 3": "/devices/pixel-watch.png",
  "Instinct Crossover": "/devices/pixel-watch.png",
  "Instinct E": "/devices/pixel-watch.png",
  "iPad": "/ipadbase.png",
  "iPad 10th Gen": "/devices/ipad-10.webp",
  "iPad 9th Gen": "/devices/ipad-9.webp",
  "iPad Air": "/ipadair.png",
  "iPad Air 11\" M2": "/devices/ipad-air-11-m2.webp",
  "iPad Air 11\" M3": "/devices/ipad-air-11-m3.webp",
  "iPad Air 13\" M2": "/devices/ipad-air-13-m2.webp",
  "iPad Air 13\" M3": "/devices/ipad-air-13-m3.webp",
  "iPad Mini": "/ipadmini.png",
  "iPad Mini 6th Gen": "/devices/ipad-mini-6.webp",
  "iPad Mini 7th Gen": "/devices/ipad-mini-7.webp",
  "iPad Pro": "/ipadpro.png",
  "iPad Pro 11\" 4th Gen": "/devices/ipad-pro-11-4g.webp",
  "iPad Pro 11\" M4": "/devices/ipad-pro-11-m4.webp",
  "iPad Pro 11\" M5": "/devices/ipad-pro-11-m5.webp",
  "iPad Pro 12.9\" 6th Gen": "/devices/ipad-pro-12-9.webp",
  "iPad Pro 13\" M4": "/devices/ipad-pro-13-m4.webp",
  "iPad Pro 13\" M5": "/devices/ipad-pro-13-m5.webp",
  "iPhone 11": "/iphone11.png",
  "iPhone 11 Pro": "/devices/bm/iphone-11-pro.png",
  "iPhone 11 Pro Max": "/devices/bm/iphone-11-pro-max.png",
  "iPhone 12": "/iphone12.png",
  "iPhone 12 Mini": "/devices/bm/iphone-12-mini.png",
  "iPhone 12 Pro": "/devices/bm/iphone-12-pro.png",
  "iPhone 12 Pro Max": "/devices/bm/iphone-12-pro-max.png",
  "iPhone 13": "/iphone13.png",
  "iPhone 13 Pro": "/devices/bm/iphone-13-pro.png",
  "iPhone 13 Pro Max": "/devices/bm/iphone-13-pro-max.png",
  "iPhone 14": "/iphone14.png",
  "iPhone 14 Plus": "/devices/bm/iphone-14-plus.png",
  "iPhone 14 Pro": "/devices/bm/iphone-14-pro.png",
  "iPhone 14 Pro Max": "/devices/bm/iphone-14-pro-max.png",
  "iPhone 15": "/iphone15.png",
  "iPhone 15 Plus": "/devices/bm/iphone-15-plus.png",
  "iPhone 15 Pro": "/devices/bm/iphone-15-pro.png",
  "iPhone 15 Pro Max": "/devices/bm/iphone-15-pro-max.png",
  "iPhone 16": "/iphone16.png",
  "iPhone 16 Plus": "/devices/iphone-16-plus-test.png",
  "iPhone 16 Pro": "/devices/bm/iphone-16-pro.png",
  "iPhone 16 Pro Max": "/devices/iphone-16-pro-max-test.png",
  "iPhone 16E": "/devices/iphone-16e-test.png",
  "iPhone 17": "/iphone17.png",
  "iPhone 17 Air": "/devices/iphone-17-air-test.png",
  "iPhone 17 Pro": "/devices/iphone-17-pro-test.png",
  "iPhone 17 Pro Max": "/devices/iphone-17-pro-max-test.png",
  "iPhone 17E": "/iphone17e.png",
  "Latitude": "/devices/dell-latitude.jpg",
  "Latitude 3000": "/devices/dell-latitude.jpg",
  "Latitude 3300 Series": "/devices/dell-latitude-latitude_3000-3000_latitude-3000-13.png",
  "Latitude 3400 Series": "/devices/dell-latitude-latitude_3000-3000_latitude-3000-14.png",
  "Latitude 3500 Series": "/devices/dell-latitude-latitude_3000-3000_latitude-3000-15.png",
  "Latitude 5000": "/devices/dell-latitude.jpg",
  "Latitude 5200 Series": "/devices/dell-latitude-latitude_5000-5000_latitude-5000-12.png",
  "Latitude 5300 Series": "/devices/dell-latitude-latitude_5000-5000_latitude-5000-13.png",
  "Latitude 5400 Series": "/devices/dell-latitude-latitude_5000-5000_latitude-5000-14.png",
  "Latitude 5430 Rugged": "/devices/d_lat_rugged_5430.png",
  "Latitude 5500 Series": "/devices/dell-latitude-latitude_5000-5000_latitude-5000-15.png",
  "Latitude 5540": "/devices/dell-latitude.jpg",
  "Latitude 7000": "/devices/dell-latitude.jpg",
  "Latitude 7200 Series": "/devices/dell-latitude-latitude_7000-7000_latitude-7000-12.png",
  "Latitude 7300 Series": "/devices/dell-latitude-latitude_7000-7000_latitude-7000-13.png",
  "Latitude 7330 Rugged Extreme": "/devices/d_lat_rugged_7330_extreme.png",
  "Latitude 7400 Series": "/devices/dell-latitude-latitude_7000-7000_latitude-7000-14.png",
  "Latitude 7440": "/devices/dell-latitude.jpg",
  "Latitude 7500 Series": "/devices/dell-latitude-latitude_7000-7000_latitude-7000-15.png",
  "Latitude 7600 Series": "/devices/dell-latitude-latitude_7000-7000_latitude-7000-16.png",
  "Latitude 9000": "/devices/dell-latitude.jpg",
  "Latitude 9300 Series": "/devices/dell-latitude-latitude_9000-9000_latitude-9000-13.png",
  "Latitude 9400 Series": "/devices/dell-latitude-latitude_9000-9000_latitude-9000-14.png",
  "Latitude 9500 Series": "/devices/dell-latitude-latitude_9000-9000_latitude-9000-15.png",
  "Latitude Rugged": "/devices/dell-latitude.jpg",
  "Legion": "/devices/lenovo-laptop-generic.svg",
  "Legion 5": "/devices/lenovo-laptop-generic.svg",
  "Legion 5 Pro": "/devices/lenovo-laptop-generic.svg",
  "Legion 5i": "/devices/lenovo-laptop-generic.svg",
  "Legion 5i Pro": "/devices/lenovo-laptop-generic.svg",
  "Legion 7": "/devices/lenovo-laptop-generic.svg",
  "Legion 7 Pro": "/devices/lenovo-laptop-generic.svg",
  "Legion 7i": "/devices/lenovo-laptop-generic.svg",
  "Legion 7i Pro": "/devices/lenovo-laptop-generic.svg",
  "Legion 9i": "/devices/lenovo-laptop-generic.svg",
  "Legion Slim 5": "/devices/lenovo-laptop-generic.svg",
  "Legion Slim 5i": "/devices/lenovo-laptop-generic.svg",
  "Legion Slim 7": "/devices/lenovo-laptop-generic.svg",
  "Legion Slim 7i": "/devices/lenovo-laptop-generic.svg",
  "Legion Tower 5i": "/devices/lenovo-thinkcentre-tower.webp",
  "Legion Tower 7i": "/devices/lenovo-thinkcentre-tower.webp",
  "Legion Y520": "/devices/lenovo-laptop-generic.svg",
  "Legion Y530": "/devices/lenovo-laptop-generic.svg",
  "Legion Y540": "/devices/lenovo-laptop-generic.svg",
  "Legion Y545": "/devices/lenovo-laptop-generic.svg",
  "Legion Y730": "/devices/lenovo-laptop-generic.svg",
  "Legion Y740": "/devices/lenovo-laptop-generic.svg",
  "LG Gram 14 (14Z90R, 2023)": "/devices/lg_gr14_23.png",
  "LG Gram 14 (14Z90S, 2024)": "/devices/lg_gr14_24.png",
  "LG Gram 14 2-in-1 (14T90R, 2023)": "/devices/lg_gr14t_23.png",
  "LG Gram 14 2-in-1 (14T90S, 2024)": "/devices/lg_gr14t_24.png",
  "LG Gram 15 (15Z90R, 2023)": "/devices/lg_gr15_23.png",
  "LG Gram 16 (16Z90R, 2023)": "/devices/lg_gr16_23.png",
  "LG Gram 16 (16Z90S, 2024)": "/devices/lg_gr16_24.png",
  "LG Gram 16 2-in-1 (16T90R, 2023)": "/devices/lg_gr16t_23.png",
  "LG Gram 16 2-in-1 (16T90S, 2024)": "/devices/lg_gr16t_24.png",
  "LG Gram 17 (17Z90R, 2023)": "/devices/lg_gr17_23.png",
  "LG Gram 17 (17Z90S, 2024)": "/devices/lg_gr17_24.png",
  "LG Gram Pro 16 (16Z90SP, 2024)": "/devices/lg_grpro16_24.png",
  "LG Gram Pro 16 (16Z90TR, 2025)": "/devices/lg_grpro16_25.png",
  "LG Gram Pro 16 2-in-1 (16T90SP, 2024)": "/devices/lg_grpro16t_24.png",
  "LG Gram Pro 17 (17Z90SP, 2024)": "/devices/lg_grpro17_24.png",
  "LG Gram Pro 17 (17Z90TR, 2025)": "/devices/lg_grpro17_25.png",
  "LG Gram Style 14 (14Z90RS, 2023)": "/devices/lg_grstyle14.png",
  "LG Gram Style 16 (16Z90RS, 2023)": "/devices/lg_grstyle16.png",
  "LG Gram SuperSlim 15 (15Z90RT, 2023)": "/devices/lg_grultra15.png",
  "Lily 2": "/devices/pixel-watch.png",
  "Lily 2 Active": "/devices/pixel-watch.png",
  "Lily 2 Classic": "/devices/pixel-watch.png",
  "LOQ": "/devices/lenovo-laptop-generic.svg",
  "LOQ 15": "/devices/lenovo-laptop-generic.svg",
  "LOQ 17": "/devices/lenovo-laptop-generic.svg",
  "M Series": "/devices/alienware-m18.webp",
  "Mac Mini M1": "/devices/mac-mini-m1.webp",
  "Mac Mini M2": "/devices/mac-mini-m2.webp",
  "Mac Mini M4": "/devices/mac-mini-m2.webp",
  "Mac Mini M4 Pro": "/devices/mac-mini-m2.webp",
  "Mac Pro M2 Ultra": "/devices/mac-pro-m2.webp",
  "Mac Studio M2 Max": "/devices/mac-studio-m2.webp",
  "Mac Studio M2 Ultra": "/devices/mac-studio-m2.webp",
  "Mac Studio M4 Max": "/devices/mac-studio-m2.webp",
  "Mac Studio M4 Ultra": "/devices/mac-studio-m2.webp",
  "MacBook": "/macbook-classic-series.webp",
  "MacBook Air": "/macbook-air-series.webp",
  "MacBook Air 13\" M1 (2020)": "/devices/macbook-air-m1.webp",
  "MacBook Air 13\" M2 (2022)": "/devices/macbook-air-m2.webp",
  "MacBook Air 13\" M3 (2024)": "/devices/macbook-air-m3.webp",
  "MacBook Air 15\" M2 (2023)": "/devices/macbook-air-m2.webp",
  "MacBook Air 15\" M3 (2024)": "/devices/macbook-air-m3.webp",
  "MacBook Air M4 (13\" & 15\", 2025)": "/devices/macbook-air-m3.webp",
  "MacBook Air M5 (13\" & 15\", 2026)": "/devices/macbook-air-m3.webp",
  "MacBook Neo": "/macbook-classic-series.webp",
  "MacBook Pro": "/macbook-pro-series.webp",
  "MacBook Pro 13\" Intel (2020)": "/devices/macbook-pro-m1.webp",
  "MacBook Pro 13\" M1 (2020)": "/devices/macbook-pro-m1.webp",
  "MacBook Pro 14\" M2 (2023)": "/devices/macbook-pro-m2.webp",
  "MacBook Pro 14\" M3 (2023)": "/devices/macbook-pro-m3.webp",
  "MacBook Pro 14\" M4 (2024)": "/devices/macbook-pro-m4.webp",
  "MacBook Pro 14\" M5 (2025)": "/devices/macbook-pro-m4.webp",
  "MacBook Pro 14\" M5 (2026)": "/devices/macbook-pro-m4.webp",
  "MacBook Pro 16\" Intel (2019)": "/devices/macbook-pro-m1.webp",
  "MacBook Pro 16\" M2 (2023)": "/devices/macbook-pro-m2.webp",
  "MacBook Pro 16\" M3 (2023)": "/devices/macbook-pro-m3.webp",
  "MacBook Pro 16\" M4 (2024)": "/devices/macbook-pro-m4.webp",
  "MacBook Pro 16\" M5 (2026)": "/devices/macbook-pro-m4.webp",
  "MacBook Pro Retina 13\"/15\" (2014)": "/devices/macbook-pro-m1.webp",
  "MacBook Pro Retina 13\"/15\" (2015)": "/devices/macbook-pro-m1.webp",
  "MacBook Pro Touch Bar 13\"/15\" (2016–2017)": "/devices/macbook-pro-m1.webp",
  "MacBook Pro Touch Bar 13\"/15\" (2018–2019)": "/devices/macbook-pro-m1.webp",
  "MARQ Adventurer": "/devices/pixel-watch.png",
  "MARQ Athlete": "/devices/pixel-watch.png",
  "MARQ Aviator": "/devices/pixel-watch.png",
  "MARQ Captain": "/devices/pixel-watch.png",
  "MARQ Commander": "/devices/pixel-watch.png",
  "MARQ Golfer": "/devices/pixel-watch.png",
  "Meta Quest 2 (128GB)": "/devices/meta-quest-2.png",
  "Meta Quest 2 (256GB)": "/devices/meta-quest-2.png",
  "Meta Quest 3 (128GB)": "/devices/meta-quest-3.png",
  "Meta Quest 3 (512GB)": "/devices/meta-quest-3.png",
  "Meta Quest 3S (128GB)": "/devices/meta-quest-3s.png",
  "Meta Quest 3S (256GB)": "/devices/meta-quest-3s.png",
  "Meta Quest Pro": "/devices/meta-quest-pro.png",
  "Nintendo Switch Lite": "/devices/switch-lite.webp",
  "Nintendo Switch OLED": "/devices/switch-oled.webp",
  "Nintendo Switch V2": "/devices/switch-oled.webp",
  "Nitro": "/devices/acer-nitro-acer-nitro-16.png",
  "Nitro 5": "/devices/acer-nitro-acer-nitro-5.png",
  "Nitro V": "/devices/acer-nitro-acer-nitro-v.png",
  "Note Series": "/devices/gnote20u.webp",
  "Notebook": "/devices/hp-notebook-hp-notebook-15.png",
  "Notebook 14": "/devices/hp-notebook-hp-notebook-14.png",
  "Notebook 15": "/devices/hp-notebook-hp-notebook-15.png",
  "Notebook 17": "/devices/hp-notebook-hp-notebook-17.png",
  "NUC 14 Pro": "/devices/asus-rog-desktop.webp",
  "OMEN": "/devices/hp-omen-omen_std-hp-omen-17.png",
  "OMEN 15": "/devices/hp-omen-omen_std-hp-omen-15.png",
  "OMEN 16": "/devices/hp-omen-omen_std-hp-omen-16.png",
  "OMEN 17": "/devices/hp-omen-omen_std-hp-omen-17.png",
  "OMEN 40L Desktop": "/devices/hp-omen-35l.webp",
  "OMEN 45L Desktop": "/devices/hp-omen-45l.webp",
  "OMEN Max": "/devices/hp_omen_max.png",
  "OMEN Slim": "/devices/hp_omen_slim.png",
  "OMEN Transcend": "/devices/hp-omen-omen_trans-hp-omen-transcend-16.png",
  "OMEN Transcend 14": "/devices/hp-omen-omen_trans-hp-omen-transcend-14.png",
  "OMEN Transcend 16": "/devices/hp-omen-omen_trans-hp-omen-transcend-16.png",
  "OmniBook": "/devices/hp-omnibook-hp-omnibook-x.png",
  "OmniBook 3": "/devices/hp-omnibook-hp-omnibook-3.png",
  "OmniBook 7": "/devices/hp-omnibook-hp-omnibook-7.png",
  "OmniBook 7 Aero": "/devices/hp-omnibook-hp-omnibook-7-aero.png",
  "OmniBook 7 Flip": "/devices/hp-omnibook-hp-omnibook-7-flip.png",
  "OmniBook X": "/devices/hp-omnibook-hp-omnibook-x.png",
  "OmniBook X Flip": "/devices/hp-omnibook-hp-omnibook-x-flip.png",
  "OptiPlex 5000": "/devices/dell-optiplex-sff.webp",
  "OptiPlex 7010": "/devices/dell-optiplex-tower.webp",
  "Pavilion": "/devices/hp-pavilion-hp-pavilion-15.png",
  "Pavilion 14": "/devices/hp-pavilion-hp-pavilion-14.png",
  "Pavilion 16": "/devices/hp-pavilion-hp-pavilion-16.png",
  "Pavilion 32 All-in-One": "/devices/lenovo-ideacentre.webp",
  "Pavilion Gaming": "/devices/hp-pavilion-hp-pavilion-gaming.png",
  "Pavilion x360": "/devices/hp-pavilion-hp-pavilion-x360.png",
  "Pixel 10": "/devices/px10.webp",
  "Pixel 10 Pro": "/devices/px10p.webp",
  "Pixel 10 Pro Fold": "/devices/px10pfold.webp",
  "Pixel 10 Pro XL": "/devices/px10pxl.webp",
  "Pixel 10a": "/devices/px10a.webp",
  "Pixel 5": "/devices/px5.webp",
  "Pixel 5a (5G)": "/devices/px5a.webp",
  "Pixel 6": "/devices/pixel-6.webp",
  "Pixel 6 Pro": "/devices/pixel-6-pro.webp",
  "Pixel 6a": "/devices/pixel-6a.webp",
  "Pixel 7": "/devices/pixel-7.webp",
  "Pixel 7 Pro": "/devices/pixel-7-pro.webp",
  "Pixel 7a": "/devices/pixel-7a.webp",
  "Pixel 8": "/devices/pixel-8.webp",
  "Pixel 8 Pro": "/devices/pixel-8-pro.webp",
  "Pixel 8a": "/devices/pixel-8a.webp",
  "Pixel 9": "/devices/pixel-9.webp",
  "Pixel 9 Pro": "/devices/pixel-9-pro.webp",
  "Pixel 9 Pro Fold": "/devices/px9pfold.webp",
  "Pixel 9 Pro XL": "/devices/pixel-9-pro-xl.webp",
  "Pixel 9a": "/devices/pixel-9a.webp",
  "Pixel Fold": "/devices/pxfold.webp",
  "Pixel Tablet": "/devices/pixel-tablet.webp",
  "Pixel Watch": "/devices/pixel-watch.jpg",
  "Pixel Watch 2": "/devices/pixel-watch.jpg",
  "Pixel Watch 3": "/devices/pixel-watch.jpg",
  "PlayStation 4": "/ps4-series.webp",
  "PlayStation 4 (Standard)": "/devices/ps4.webp",
  "PlayStation 4 Pro": "/devices/ps4-pro.webp",
  "PlayStation 4 Slim": "/devices/ps4-slim.webp",
  "PlayStation 5": "/devices/ps5.webp",
  "PlayStation 5 Pro": "/devices/ps5pro.webp",
  "PlayStation 5 Slim": "/devices/ps5-slim-disc.webp",
  "Precision": "/devices/dell-latitude.jpg",
  "Precision 3000": "/devices/dell-latitude.jpg",
  "Precision 3400 Series": "/devices/dell-precision-precision_3000-3000_precision-3000-series-14.png",
  "Precision 3500 Series": "/devices/dell-precision-precision_3000-3000_precision-3000-series-15.png",
  "Precision 3680": "/devices/dell-optiplex-tower.webp",
  "Precision 5000": "/devices/dell-latitude.jpg",
  "Precision 5540": "/devices/dell-precision-precision_3000-3000_precision-3000-series-15.png",
  "Precision 5550": "/devices/dell-precision-precision_3000-3000_precision-3000-series-15.png",
  "Precision 5560": "/devices/dell-precision-precision_3000-3000_precision-3000-series-15.png",
  "Precision 7000": "/devices/dell-latitude.jpg",
  "Precision 7560": "/devices/dell-precision-precision_3000-3000_precision-3000-series-15.png",
  "Precision 7760": "/devices/dell-precision-precision_3000-3000_precision-3000-series-15.png",
  "Precision 7770": "/devices/dell-precision-precision_3000-3000_precision-3000-series-15.png",
  "Precision 7780": "/devices/dell-precision-precision_3000-3000_precision-3000-series-15.png",
  "Predator": "/devices/acer-predator-acer-predator-helios.png",
  "Predator Helios": "/devices/acer-predator-acer-predator-helios.png",
  "Predator Triton": "/devices/acer-predator-acer-predator-triton.png",
  "PRO DP180": "/devices/msi-aegis.webp",
  "Pro Series": "/pixel-pro-series.webp",
  "ProArt": "/devices/asus-proart-proart-p16.png",
  "ProArt P16": "/devices/asus-proart-proart-p16.png",
  "ProArt PX13": "/devices/asus-proart-proart-px13.png",
  "ProArt PZ13": "/devices/asus-proart-proart-pz13.png",
  "ProArt Studiobook 16": "/devices/asus-proart-proart-studiobook-16.png",
  "ProArt Studiobook Pro 16": "/devices/asus-proart-proart-studiobook-pro-16.png",
  "ProBook": "/devices/hp-probook-hp-probook-g11.png",
  "ProBook G10": "/devices/hp-probook-hp-probook-g10.png",
  "ProBook G11": "/devices/hp-probook-hp-probook-g11.png",
  "ProBook G5": "/devices/hp-probook-hp-probook-g5.png",
  "ProBook G6": "/devices/hp-probook-hp-probook-g6.png",
  "ProBook G7": "/devices/hp-probook-hp-probook-g7.png",
  "ProBook G8": "/devices/hp-probook-hp-probook-g8.png",
  "ProBook G9": "/devices/hp-probook-hp-probook-g9.png",
  "ProDesk 400 G9": "/devices/hp-prodesk-400.webp",
  "Quatix 6": "/devices/pixel-watch.png",
  "Quatix 7": "/devices/pixel-watch.png",
  "Quatix 8": "/devices/pixel-watch.png",
  "ROG": "/devices/asus-rog-strix.webp",
  "ROG Flow": "/devices/asus-rog-zephyrus.webp",
  "ROG Flow X13 GV301": "/devices/asus-rog-republic-of-gamers-flow-x13-gv301.png",
  "ROG Flow X13 GV302": "/devices/asus-rog-republic-of-gamers-flow-x13-gv302.png",
  "ROG Flow X16 GV601": "/devices/asus-rog-republic-of-gamers-flow-x16-gv601.png",
  "ROG Flow Z13 ACRNM RMT02 GZ301": "/devices/asus-rog-republic-of-gamers-flow-z13-acrnm-rmt02-gz301.png",
  "ROG Flow Z13 GZ301": "/devices/asus-rog-republic-of-gamers-flow-z13-gz301.png",
  "ROG Flow Z13 GZ302": "/devices/asus-rog-republic-of-gamers-flow-z13-gz302.png",
  "ROG Flow Z13-KJP GZ302": "/devices/asus-rog-republic-of-gamers-flow-z13-kjp-gz302.png",
  "ROG NUC": "/devices/asus-rog-desktop.webp",
  "ROG Strix": "/devices/asus-rog-strix.webp",
  "ROG Strix G15 G512": "/devices/asus-rog-republic-of-gamers-strix-g15-g512.png",
  "ROG Strix G15 G513": "/devices/asus-rog-republic-of-gamers-strix-g15-g513.png",
  "ROG Strix G16 G614": "/devices/asus-rog-republic-of-gamers-strix-g16-g614.png",
  "ROG Strix G16 G615": "/devices/asus-rog-republic-of-gamers-strix-g16-g615.png",
  "ROG Strix G16CH": "/devices/asus-rog-desktop.webp",
  "ROG Strix G17 G712": "/devices/asus-rog-republic-of-gamers-strix-g17-g712.png",
  "ROG Strix G17 G713": "/devices/asus-rog-republic-of-gamers-strix-g17-g713.png",
  "ROG Strix G18 G814": "/devices/asus-rog-republic-of-gamers-strix-g18-g814.png",
  "ROG Strix G18 G815": "/devices/asus-rog-republic-of-gamers-strix-g18-g815.png",
  "ROG Strix G531": "/devices/asus-rog-republic-of-gamers-strix-g531.png",
  "ROG Strix G731": "/devices/asus-rog-republic-of-gamers-strix-g731.png",
  "ROG Strix Scar 15 G532": "/devices/asus-rog-republic-of-gamers-strix-scar-15-g532.png",
  "ROG Strix Scar 15 G533": "/devices/asus-rog-republic-of-gamers-strix-scar-15-g533.png",
  "ROG Strix Scar 16 G634": "/devices/asus-rog-republic-of-gamers-strix-scar-16-g634.png",
  "ROG Strix Scar 16 G635": "/devices/asus-rog-republic-of-gamers-strix-scar-16-g635.png",
  "ROG Strix Scar 17 G732": "/devices/asus-rog-republic-of-gamers-strix-scar-17-g732.png",
  "ROG Strix Scar 17 G733": "/devices/asus-rog-republic-of-gamers-strix-scar-17-g733.png",
  "ROG Strix Scar 17 SE G733": "/devices/asus-rog-republic-of-gamers-strix-scar-17-se-g733.png",
  "ROG Strix Scar 18 G834": "/devices/asus-rog-republic-of-gamers-strix-scar-18-g834.png",
  "ROG Strix Scar 18 G835": "/devices/asus-rog-republic-of-gamers-strix-scar-18-g835.png",
  "ROG Zephyrus": "/devices/asus-rog-zephyrus.webp",
  "ROG Zephyrus Duo 15 GX550": "/devices/asus-rog-republic-of-gamers-zephyrus-duo-15-gx550.png",
  "ROG Zephyrus Duo 15 SE GX551": "/devices/asus-rog-republic-of-gamers-zephyrus-duo-15-se-gx551.png",
  "ROG Zephyrus Duo 16 GX650": "/devices/asus-rog-republic-of-gamers-zephyrus-duo-16-gx650.png",
  "ROG Zephyrus G14 GA401": "/devices/asus-rog-republic-of-gamers-zephyrus-g14-ga401.png",
  "ROG Zephyrus G14 GA402": "/devices/asus-rog-republic-of-gamers-zephyrus-g14-ga402.png",
  "ROG Zephyrus G14 GA403": "/devices/asus-rog-republic-of-gamers-zephyrus-g14-ga403.png",
  "ROG Zephyrus G15 GA502": "/devices/asus-rog-republic-of-gamers-zephyrus-g15-ga502.png",
  "ROG Zephyrus G15 GA503": "/devices/asus-rog-republic-of-gamers-zephyrus-g15-ga503.png",
  "ROG Zephyrus G16 GA605": "/devices/asus-rog-republic-of-gamers-zephyrus-g16-ga605.png",
  "ROG Zephyrus G16 GU603": "/devices/asus-rog-republic-of-gamers-zephyrus-g16-gu603.png",
  "ROG Zephyrus G16 GU605": "/devices/asus-rog-republic-of-gamers-zephyrus-g16-gu605.png",
  "ROG Zephyrus M GM501": "/devices/asus-rog-republic-of-gamers-zephyrus-m-gm501.png",
  "ROG Zephyrus M15 GU502": "/devices/asus-rog-republic-of-gamers-zephyrus-m15-gu502.png",
  "ROG Zephyrus M16 GU603": "/devices/asus-rog-republic-of-gamers-zephyrus-m16-gu603.png",
  "ROG Zephyrus M16 GU604": "/devices/asus-rog-republic-of-gamers-zephyrus-m16-gu604.png",
  "ROG Zephyrus S GX531": "/devices/asus-rog-republic-of-gamers-zephyrus-s-gx531.png",
  "ROG Zephyrus S15 GX502": "/devices/asus-rog-republic-of-gamers-zephyrus-s15-gx502.png",
  "ROG Zephyrus S17 GX701": "/devices/asus-rog-republic-of-gamers-zephyrus-s17-gx701.png",
  "ROG Zephyrus S17 GX703": "/devices/asus-rog-republic-of-gamers-zephyrus-s17-gx703.png",
  "Rugged": "/devices/dell-latitude.jpg",
  "S Series": "/s-series.png",
  "Slim": "/devices/lenovo-laptop-generic.svg",
  "Slim 7": "/devices/lenovo-laptop-generic.svg",
  "Slim 7 Pro X": "/devices/lenovo-laptop-generic.svg",
  "Slim 7i": "/devices/lenovo-laptop-generic.svg",
  "Slim 7i Pro X": "/devices/lenovo-laptop-generic.svg",
  "Slim Pro 7": "/devices/lenovo-laptop-generic.svg",
  "Slim Pro 9i": "/devices/lenovo-laptop-generic.svg",
  "Spectre": "/devices/hp-spectre-hp-spectre-14-x360.png",
  "Spectre x360 13": "/devices/hp-spectre-hp-spectre-13-x360.png",
  "Spectre x360 14": "/devices/hp-spectre-hp-spectre-14-x360.png",
  "Spectre x360 15": "/devices/hp-spectre-hp-spectre-15-x360.png",
  "Spectre x360 16": "/devices/hp-spectre-hp-spectre-16-x360.png",
  "Standard Series": "/pixel-standard-series.webp",
  "ThinkBook": "/devices/ln_tb_14.png",
  "ThinkBook 13s": "/devices/ln_tb_13s.png",
  "ThinkBook 13x": "/devices/ln_tb_13x.png",
  "ThinkBook 14": "/devices/ln_tb_14.png",
  "ThinkBook 14p": "/devices/ln_tb_14p.png",
  "ThinkBook 14s": "/devices/ln_tb_14s.png",
  "ThinkBook 14s Yoga": "/devices/ln_tb_14s_yoga.png",
  "ThinkBook 15": "/devices/ln_tb_15.png",
  "ThinkBook 15p": "/devices/ln_tb_15p.png",
  "ThinkBook 16": "/devices/ln_tb_16.png",
  "ThinkBook 16p": "/devices/ln_tb_16p.png",
  "ThinkCentre M90q Tiny": "/devices/lenovo-thinkcentre-tiny.webp",
  "ThinkCentre M920": "/devices/lenovo-thinkcentre-tower.webp",
  "ThinkPad E": "/devices/ln_tp_e14_g7.png",
  "ThinkPad E14 Gen 5": "/devices/ln_tp_e14_g5.png",
  "ThinkPad E14 Gen 6": "/devices/ln_tp_e14_g6.png",
  "ThinkPad E14 Gen 7": "/devices/ln_tp_e14_g7.png",
  "ThinkPad E15": "/devices/ln_tp_e15.png",
  "ThinkPad E16 Gen 1": "/devices/ln_tp_e16_g1.png",
  "ThinkPad E16 Gen 2": "/devices/ln_tp_e16_g2.png",
  "ThinkPad E16 Gen 3": "/devices/ln_tp_e16_g3.png",
  "ThinkPad L": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L13 Gen 1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L13 Gen 2": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L13 Gen 3": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L13 Gen 4": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L13 Gen 5": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L14 Gen 1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L14 Gen 2": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L14 Gen 3": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L14 Gen 4": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L14 Gen 5": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L14 Gen 6": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L15 Gen 1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L15 Gen 2": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L15 Gen 3": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L15 Gen 4": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L16 Gen 1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad L16 Gen 2": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad P": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad P50": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad P51": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad P52": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad P53": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad P70": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad P71": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad P72": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad P73": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad T": "/devices/ln_tp_t.png",
  "ThinkPad T-Series": "/devices/ln_tp_t.png",
  "ThinkPad X1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 2-in-1 Gen 10": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 2-in-1 Gen 9": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Carbon Gen 10": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Carbon Gen 11": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Carbon Gen 12": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Carbon Gen 13": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Carbon Gen 6": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Carbon Gen 7": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Carbon Gen 8": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Carbon Gen 9": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Extreme Gen 1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Extreme Gen 2": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Extreme Gen 3": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Extreme Gen 4": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Extreme Gen 5": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Fold": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Nano Gen 1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Nano Gen 2": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Nano Gen 3": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Titanium Yoga": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Yoga Gen 3": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Yoga Gen 4": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Yoga Gen 5": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Yoga Gen 6": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Yoga Gen 7": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X1 Yoga Gen 8": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 2-in-1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 Gen 1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 Gen 2": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 Gen 3": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 Gen 4": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 Gen 5": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 Gen 6": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 Yoga Gen 1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 Yoga Gen 2": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 Yoga Gen 3": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13 Yoga Gen 4": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X13s": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad X390": "/devices/ln_tp_x390.png",
  "ThinkPad X390 Yoga": "/devices/ln_tp_x390_yoga.png",
  "ThinkPad X9": "/devices/ln_tp_x9_14.png",
  "ThinkPad X9 14": "/devices/ln_tp_x9_14.png",
  "ThinkPad X9 15": "/devices/ln_tp_x9_15.png",
  "ThinkPad Z": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad Z13 Gen 1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad Z13 Gen 2": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad Z16 Gen 1": "/devices/lenovo-laptop-generic.svg",
  "ThinkPad Z16 Gen 2": "/devices/lenovo-laptop-generic.svg",
  "Trident 3": "/devices/msi-trident.webp",
  "Trident AS": "/devices/msi-trident.webp",
  "Trident X": "/devices/msi-trident.webp",
  "Trident X2": "/devices/msi-trident.webp",
  "TUF A14": "/devices/asus-tuf-tuf-a14-laptop.png",
  "TUF A15": "/devices/asus-tuf-tuf-a15-laptop.png",
  "TUF A16": "/devices/asus-tuf-tuf-a16-laptop.png",
  "TUF A17": "/devices/asus-tuf-tuf-a17-laptop.png",
  "TUF A18": "/devices/asus-tuf-tuf-a18-laptop.png",
  "TUF F15": "/devices/asus-tuf-tuf-f15-laptop.png",
  "TUF F16": "/devices/asus-tuf-tuf-f16-laptop.png",
  "TUF F17": "/devices/asus-tuf-tuf-f17-laptop.png",
  "TUF Gaming": "/devices/asus-tuf-gaming.webp",
  "TUF Gaming FX10CP": "/devices/asus-rog-desktop.webp",
  "TUF Gaming T500 (2025)": "/devices/asus-rog-desktop.webp",
  "TUF Gaming TM500 (2026)": "/devices/asus-rog-desktop.webp",
  "Venu 2": "/devices/pixel-watch.png",
  "Venu 4": "/devices/pixel-watch.png",
  "Venu X1": "/devices/pixel-watch.png",
  "Victus": "/devices/hp-spectre-x360.webp",
  "Victus 15": "/devices/hp_victus_15.png",
  "Vivoactive 4": "/devices/pixel-watch.png",
  "Vivoactive 4S": "/devices/pixel-watch.png",
  "Vivoactive 5": "/devices/pixel-watch.png",
  "Vivoactive 6": "/devices/pixel-watch.png",
  "Vivobook": "/devices/asus-vivobook.webp",
  "Vivobook 14": "/devices/asus-vivobook.webp",
  "Vivobook 15": "/devices/asus-vivobook.webp",
  "Vivobook 16": "/devices/asus-vivobook.webp",
  "Vostro": "/devices/dell-inspiron-15.webp",
  "Vostro 3000": "/devices/dell-inspiron-15.webp",
  "Vostro 3420": "/devices/dell-vostro-vostro_3000-3000_3420.png",
  "Vostro 3430": "/devices/dell-vostro-vostro_3000-3000_3430.png",
  "Vostro 3500": "/devices/dell-latitude-latitude_3000-3000_latitude-3000-15.png",
  "Vostro 3510": "/devices/dell-vostro-vostro_3000-3000_3510.png",
  "Vostro 3520": "/devices/dell-vostro-vostro_3000-3000_3520.png",
  "Vostro 3530": "/devices/dell-vostro-vostro_3000-3000_3530.png",
  "Vostro 3535": "/devices/dell-vostro-vostro_3000-3000_3535.png",
  "Vostro 3590": "/devices/dell-vostro-vostro_3000-3000_3590.png",
  "Vostro 3591": "/devices/dell-vostro-vostro_3000-3000_3591.png",
  "Vostro 5000": "/devices/dell-inspiron-15.webp",
  "Vostro 5301": "/devices/dell-vostro-vostro_5000-5000_5301.png",
  "Vostro 5401": "/devices/dell-vostro-vostro_5000-5000_5401.png",
  "Vostro 5402": "/devices/dell-vostro-vostro_5000-5000_5402.png",
  "Vostro 5410": "/devices/dell-vostro-vostro_5000-5000_5410.png",
  "Vostro 5490": "/devices/dell-vostro-vostro_5000-5000_5490.png",
  "Vostro 5501": "/devices/dell-vostro-vostro_5000-5000_5501.png",
  "Vostro 5502": "/devices/dell-vostro-vostro_5000-5000_5502.png",
  "Vostro 5510": "/devices/dell-vostro-vostro_5000-5000_5510.png",
  "Vostro 5581": "/devices/dell-vostro-vostro_5000-5000_5581.png",
  "Vostro 5590": "/devices/dell-vostro-vostro_5000-5000_5590.png",
  "Vostro 5620": "/devices/dell-vostro-vostro_5000-5000_5620.png",
  "Vostro 5630": "/devices/dell-vostro-vostro_5000-5000_5630.png",
  "Vostro 7000": "/devices/dell-inspiron-15.webp",
  "Vostro 7500": "/devices/dell-latitude-latitude_7000-7000_latitude-7000-15.png",
  "Vostro 7510": "/devices/dell-vostro-vostro_7000-7000_7510.png",
  "Vostro 7590": "/devices/dell-xps-xps_15-15_xps-15-7590.png",
  "Vostro 7620": "/devices/dell-vostro-vostro_7000-7000_7620.png",
  "X Series": "/devices/alienware-x16.webp",
  "Xbox One": "/devices/xbox-one.webp",
  "Xbox Series S": "/devices/xbox-series-s.webp",
  "Xbox Series X": "/devices/xbox-series-x.webp",
  "XPS": "/devices/dell-xps.webp",
  "XPS 13": "/devices/dell-xps.webp",
  "XPS 13 (2023)": "/devices/dell-xps.webp",
  "XPS 13 (2024)": "/devices/dell-xps.webp",
  "XPS 13 7390": "/devices/dell-xps-xps_13-13_xps-13-7390.png",
  "XPS 13 7390 2-in-1": "/devices/dell-xps-xps_13-13_xps-13-7390-2-in-1.png",
  "XPS 13 9300": "/devices/dell-xps-xps_13-13_xps-13-9300.png",
  "XPS 13 9305": "/devices/dell-xps-xps_13-13_xps-13-9305.png",
  "XPS 13 9310": "/devices/dell-xps-xps_13-13_xps-13-9310.png",
  "XPS 13 9310 2-in-1": "/devices/dell-xps-xps_13-13_xps-13-9310-2-in-1.png",
  "XPS 13 9315": "/devices/dell-xps-xps_13-13_xps-13-9315.png",
  "XPS 13 9315 2-in-1": "/devices/dell-xps-xps_13-13_xps-13-9315-2-in-1.png",
  "XPS 13 9340": "/devices/dell-xps-xps_13-13_xps-13-9340.png",
  "XPS 13 9345": "/devices/dell-xps-xps_13-13_xps-13-9345.png",
  "XPS 13 9350": "/devices/dell-xps-xps_13-13_xps-13-9350.png",
  "XPS 13 9360": "/devices/dell-xps-xps_13-13_xps-13-9360.png",
  "XPS 13 9365 2-in-1": "/devices/dell-xps-xps_13-13_xps-13-9365-2-in-1.png",
  "XPS 13 9370": "/devices/dell-xps-xps_13-13_xps-13-9370.png",
  "XPS 13 9380": "/devices/dell-xps-xps_13-13_xps-13-9380.png",
  "XPS 13 Plus 9320": "/devices/dell-xps-xps_13-13_xps-13-plus-9320.png",
  "XPS 14": "/devices/dell-xps.webp",
  "XPS 14 9440": "/devices/dell-xps-xps_14-14_xps-14-9440.png",
  "XPS 14 DA14260": "/devices/dell-xps-xps_14-14_xps-14-da14260.png",
  "XPS 15": "/devices/dell-xps.webp",
  "XPS 15 (2023)": "/devices/dell-xps.webp",
  "XPS 15 (2024)": "/devices/dell-xps.webp",
  "XPS 15 7590": "/devices/dell-xps-xps_15-15_xps-15-7590.png",
  "XPS 15 9500": "/devices/dell-xps-xps_15-15_xps-15-9500.png",
  "XPS 15 9510": "/devices/dell-xps-xps_15-15_xps-15-9510.png",
  "XPS 15 9520": "/devices/dell-xps-xps_15-15_xps-15-9520.png",
  "XPS 15 9530": "/devices/dell-xps-xps_15-15_xps-15-9530.png",
  "XPS 15 9550": "/devices/dell-xps-xps_15-15_xps-15-9550.png",
  "XPS 15 9560": "/devices/dell-xps-xps_15-15_xps-15-9560.png",
  "XPS 15 9570": "/devices/dell-xps-xps_15-15_xps-15-9570.png",
  "XPS 15 9575 2-in-1": "/devices/dell-xps-xps_15-15_xps-15-9575-2-in-1.png",
  "XPS 16": "/devices/dell-xps.webp",
  "XPS 16 9640": "/devices/dell-xps-xps_16-16_xps-16-9640.png",
  "XPS 16 DA16260": "/devices/dell-xps-xps_16-16_xps-16-da16260.png",
  "XPS 17": "/devices/dell-xps.webp",
  "XPS 17 (2024)": "/devices/dell-xps.webp",
  "XPS 17 9700": "/devices/dell-xps-xps_17-17_xps-17-9700.png",
  "XPS 17 9710": "/devices/dell-xps-xps_17-17_xps-17-9710.png",
  "XPS 17 9720": "/devices/dell-xps-xps_17-17_xps-17-9720.png",
  "XPS 17 9730": "/devices/dell-xps-xps_17-17_xps-17-9730.png",
  "XPS Desktop 8950": "/devices/dell-xps-8950.webp",
  "XPS Desktop 8960": "/devices/dell-xps-8960.webp",
  "Yoga": "/devices/lenovo-laptop-generic.svg",
  "Yoga 6": "/devices/lenovo-laptop-generic.svg",
  "Yoga 7": "/devices/lenovo-laptop-generic.svg",
  "Yoga 710": "/devices/lenovo-laptop-generic.svg",
  "Yoga 720": "/devices/lenovo-laptop-generic.svg",
  "Yoga 7i": "/devices/lenovo-laptop-generic.svg",
  "Yoga 920": "/devices/lenovo-laptop-generic.svg",
  "Yoga 9i": "/devices/lenovo-laptop-generic.svg",
  "Yoga Book 9i": "/devices/lenovo-laptop-generic.svg",
  "Yoga C630": "/devices/lenovo-laptop-generic.svg",
  "Yoga C640": "/devices/lenovo-laptop-generic.svg",
  "Yoga C740": "/devices/lenovo-laptop-generic.svg",
  "Yoga C930": "/devices/lenovo-laptop-generic.svg",
  "Yoga C940": "/devices/lenovo-laptop-generic.svg",
  "Yoga Pro 7": "/devices/lenovo-laptop-generic.svg",
  "Yoga Pro 9i": "/devices/lenovo-laptop-generic.svg",
  "Yoga Slim 7i": "/devices/lenovo-laptop-generic.svg",
  "Yoga Slim 7x": "/devices/lenovo-laptop-generic.svg",
  "Yoga Slim 9i": "/devices/lenovo-laptop-generic.svg",
  "Z Series": "/fold-series.webp",
  "ZBook": "/devices/hp-zbook-hp-zbook-g11.png",
  "ZBook G10": "/devices/hp-zbook-hp-zbook-g10.png",
  "ZBook G11": "/devices/hp-zbook-hp-zbook-g11.png",
  "ZBook G4": "/devices/hp-zbook-hp-zbook-g4.png",
  "ZBook G5": "/devices/hp-zbook-hp-zbook-g5.png",
  "ZBook G6": "/devices/hp-zbook-hp-zbook-g6.png",
  "ZBook G7": "/devices/hp-zbook-hp-zbook-g7.png",
  "ZBook G8": "/devices/hp-zbook-hp-zbook-g8.png",
  "ZBook G9": "/devices/hp-zbook-hp-zbook-g9.png",
};

// Resolve a product image for a device model name (exact match, then
// case-insensitive). Returns null when the catalog has no image.
export function imageForModel(model?: string | null): string | null {
  if (!model) return null;
  if (DEVICE_IMAGES[model]) return DEVICE_IMAGES[model];
  const norm = model.trim().toLowerCase();
  for (const k in DEVICE_IMAGES) {
    if (k.toLowerCase() === norm) return DEVICE_IMAGES[k];
  }
  return null;
}
