import { NextRequest, NextResponse } from "next/server";
import { PRICE_TABLE, CARRIER_DEDUCTIONS, BASE_PRICED_MODELS, MACBOOK_SPECS, type MacSpec } from "../../../data/prices";
import { getResellEstimate } from "../../../lib/resell-estimates";
import skuLabelsJson from "../../../data/sku-labels.json";
import { put, list, del } from "@vercel/blob";
import { promises as fs } from "fs";
import path from "path";

const SKU_LABELS: Record<string, string> = skuLabelsJson as Record<string, string>;

// Load PC laptop additive specs from the bundled JSON file. Cached
// per-process since it's static data alongside our code.
let pcSpecsCache: Record<string, MacSpec> | null = null;
async function loadPcSpecs(): Promise<Record<string, MacSpec>> {
  if (pcSpecsCache) return pcSpecsCache;
  try {
    const p = path.join(process.cwd(), "public", "comps", "pc-laptop-specs.json");
    const raw = await fs.readFile(p, "utf-8");
    pcSpecsCache = JSON.parse(raw);
    return pcSpecsCache as Record<string, MacSpec>;
  } catch {
    return {};
  }
}

// Atlas Mobile reference — scraped by scripts/scrape-atlas-full.py.
// Read-only data shown in the admin editor for cross-reference while
// pricing TCC's grid. Cached per-process.
type AtlasReference = {
  scraped_at?: string;
  sources?: Record<string, string>;
  categories?: Record<string, Record<string, Record<string, number | null>>>;
  counts?: Record<string, number>;
};
type IwmReference = {
  scraped_at?: string;
  source?: string;
  note?: string;
  models?: Record<string, Record<string, Record<string, number>>>;
};
type EbayCell = { count: number; average: number; median: number; min: number; max: number; rejected_outliers?: number };
type EbayReference = {
  scraped_at?: string;
  source?: string;
  note?: string;
  models?: Record<string, {
    label?: string;
    family?: string;
    scraped_at?: string;
    by_cell?: Record<string, Record<string, EbayCell>>;
    samples?: Array<{ price: number; title: string; cond: string }>;
    unmatched?: number;
    outliers_rejected?: number;
  }>;
};
let atlasCache: AtlasReference | null = null;
let iwmCache: IwmReference | null = null;
let ebayCache: EbayReference | null = null;

async function loadAtlasReference(): Promise<AtlasReference> {
  if (atlasCache) return atlasCache;
  try {
    const p = path.join(process.cwd(), "public", "comps", "atlas-reference.json");
    const raw = await fs.readFile(p, "utf-8");
    atlasCache = JSON.parse(raw);
    return atlasCache as AtlasReference;
  } catch {
    return {};
  }
}

// IWM is the main competitor — useful to show staff alongside our quote
// so we can see at a glance when our price is materially below or above
// theirs. NOT a margin floor (that's Atlas). Generated by
// scripts/audit-prices-vs-iwm.py and saved to public/comps/iwm-reference.json.
async function loadIwmReference(): Promise<IwmReference> {
  if (iwmCache) return iwmCache;
  try {
    const p = path.join(process.cwd(), "public", "comps", "iwm-reference.json");
    const raw = await fs.readFile(p, "utf-8");
    iwmCache = JSON.parse(raw);
    return iwmCache as IwmReference;
  } catch {
    return {};
  }
}

// eBay sold-listings reference — actual final sale prices, bucketed by
// (storage, condition). Sealed = "Brand New" on eBay, used = "Pre-Owned",
// broken = "For parts or not working". Outliers (fake clickbait + abnormal
// extremes) rejected via IQR + half-median rule. Generated by
// scripts/scrape-ebay-sold.py and saved to public/comps/ebay-sold.json.
async function loadEbayReference(): Promise<EbayReference> {
  if (ebayCache) return ebayCache;
  try {
    const p = path.join(process.cwd(), "public", "comps", "ebay-sold.json");
    const raw = await fs.readFile(p, "utf-8");
    ebayCache = JSON.parse(raw);
    return ebayCache as EbayReference;
  } catch {
    return {};
  }
}

// Price-editor backend. Stores admin overrides as a single JSON document
// on Vercel Blob (we already use Blob for FedEx labels, so no new infra).
//
//   GET    /api/admin/prices            → public; returns
//                                          { baseline, overrides, effective,
//                                            history: [{ url, timestamp }] }
//   POST   /api/admin/prices            → auth; merges { priceTable,
//                                          carrierDeductions } into stored
//                                          overrides. Snapshots the previous
//                                          version into history before
//                                          overwriting (last 10 kept).
//   DELETE /api/admin/prices            → auth; clear ALL overrides.
//   DELETE /api/admin/prices?model=ip17p          → auth; clear one model
//                                          from both price+carrier tables.
//   DELETE /api/admin/prices?cell=ip17p/256/sealed → auth; clear one cell.
//
// Auth is the same token used by /api/admin/leads (TCC_ADMIN_TOKEN env, or
// fallback "topcash-admin-2026"). Pass via ?token= or x-admin-token header.

const ADMIN_TOKEN = process.env.TCC_ADMIN_TOKEN || "topcash-admin-2026";
const BLOB_KEY = "prices/overrides.json";
const HISTORY_PREFIX = "prices/history/";
const HISTORY_LIMIT = 10;

function checkAuth(req: NextRequest): boolean {
  const headerToken = req.headers.get("x-admin-token");
  const queryToken = req.nextUrl.searchParams.get("token");
  return headerToken === ADMIN_TOKEN || queryToken === ADMIN_TOKEN;
}

type OverridesShape = {
  priceTable: Record<string, Record<string, Record<string, number>>>;
  carrierDeductions: Record<string, Record<string, number>>;
  baseOverrides: Record<string, number>;
  // Per-model condition_adj overrides (sealed / mint / verygood / good /
  // fair / broken). Applied at customer-funnel lookup time, overriding
  // the bundled MACBOOK_SPECS[modelId].condition_adj or
  // pc-laptop-specs[modelId].condition_adj.
  conditionAdj: Record<string, Record<string, number>>;
  updatedAt?: string;
};

async function readOverrides(): Promise<OverridesShape> {
  const empty: OverridesShape = { priceTable: {}, carrierDeductions: {}, baseOverrides: {}, conditionAdj: {} };
  try {
    const { blobs } = await list({ prefix: BLOB_KEY, limit: 5 });
    const found = blobs.find((b) => b.pathname === BLOB_KEY);
    if (!found) return empty;
    const r = await fetch(found.url, { cache: "no-store" });
    if (!r.ok) return empty;
    const d = await r.json();
    return {
      priceTable: d.priceTable || {},
      carrierDeductions: d.carrierDeductions || {},
      baseOverrides: d.baseOverrides || {},
      conditionAdj: d.conditionAdj || {},
      updatedAt: d.updatedAt,
    };
  } catch {
    return empty;
  }
}

// Sparse deep-merge: prefer overlay value, fall back to base. Only used for
// the admin GET response so the editor can show the effective (post-merge)
// table without re-deriving it on the client.
function deepMerge<T>(base: T, overlay: Partial<T>): T {
  if (typeof base !== "object" || base === null) return (overlay as T) ?? base;
  if (typeof overlay !== "object" || overlay === null) return base;
  const out: Record<string, unknown> = { ...(base as Record<string, unknown>) };
  for (const k of Object.keys(overlay)) {
    const ov = (overlay as Record<string, unknown>)[k];
    const bv = (base as Record<string, unknown>)[k];
    if (ov && typeof ov === "object" && !Array.isArray(ov)) {
      out[k] = deepMerge(bv ?? {}, ov as Partial<unknown>);
    } else {
      out[k] = ov;
    }
  }
  return out as T;
}

// History: list snapshot files under prices/history/, newest first.
async function readHistory(): Promise<Array<{ url: string; pathname: string; uploadedAt: string }>> {
  try {
    const { blobs } = await list({ prefix: HISTORY_PREFIX, limit: HISTORY_LIMIT * 2 });
    return blobs
      .map((b) => ({ url: b.url, pathname: b.pathname, uploadedAt: b.uploadedAt.toISOString() }))
      .sort((a, b) => b.uploadedAt.localeCompare(a.uploadedAt))
      .slice(0, HISTORY_LIMIT);
  } catch {
    return [];
  }
}

// Snapshot the current overrides into history before overwriting. Ring-
// buffer behavior: prune anything beyond HISTORY_LIMIT.
async function snapshotToHistory(current: OverridesShape) {
  if (
    Object.keys(current.priceTable).length === 0 &&
    Object.keys(current.carrierDeductions).length === 0 &&
    Object.keys(current.baseOverrides || {}).length === 0 &&
    Object.keys(current.conditionAdj || {}).length === 0
  ) {
    return;
  }
  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  try {
    await put(`${HISTORY_PREFIX}${ts}.json`, JSON.stringify(current, null, 2), {
      access: "public",
      contentType: "application/json",
      addRandomSuffix: false,
      allowOverwrite: false,
    });
    // Prune anything beyond the limit (oldest first)
    const all = await readHistory();
    const stale = all.slice(HISTORY_LIMIT);
    for (const s of stale) {
      try { await del(s.url); } catch {}
    }
  } catch {}
}

export async function GET() {
  const overrides = await readOverrides();
  const history = await readHistory();
  const pcSpecs = await loadPcSpecs();
  const atlasReference = await loadAtlasReference();
  const iwmReference = await loadIwmReference();
  const ebayReference = await loadEbayReference();
  // Build a lightweight summary of additive-spec models so the editor can
  // render their condition_adj grids without us shipping ~1MB of full
  // spec tables across the wire. Each entry: { label, condition_adj }.
  const additive: Record<string, { source: "macbook" | "pc"; label: string; condition_adj: Record<string, number> }> = {};
  for (const [id, spec] of Object.entries(MACBOOK_SPECS)) {
    additive[id] = { source: "macbook", label: id, condition_adj: spec.condition_adj || {} };
  }
  for (const [id, spec] of Object.entries(pcSpecs)) {
    additive[id] = { source: "pc", label: id, condition_adj: (spec as MacSpec).condition_adj || {} };
  }
  // Per-model margin summary: pairs each device with our highest current
  // payout, the Atlas grade_a wholesale resell estimate, and the resulting
  // margin (resell − payout). Lets the editor show a margin chip next to
  // each device so Skywalker can spot loss-makers at a glance.
  const effectivePriceTable = deepMerge(PRICE_TABLE, overrides.priceTable);
  const marginByModel = buildMarginMap(effectivePriceTable, overrides.baseOverrides);
  return NextResponse.json({
    baseline: {
      priceTable: PRICE_TABLE,
      carrierDeductions: CARRIER_DEDUCTIONS,
      basePricedModels: BASE_PRICED_MODELS,
      additiveSpecs: additive,
    },
    overrides,
    effective: {
      priceTable: effectivePriceTable,
      carrierDeductions: deepMerge(CARRIER_DEDUCTIONS, overrides.carrierDeductions),
    },
    history,
    atlasReference,
    iwmReference,
    ebayReference,
    marginByModel,
    skuLabels: SKU_LABELS,
  });
}

type MarginRow = { label: string; payout: number; resell: number | null; margin: number | null; marginPct: number | null };
function buildMarginMap(
  effectivePriceTable: Record<string, Record<string, Record<string, number>>>,
  baseOverrides: Record<string, number>,
): Record<string, MarginRow> {
  const out: Record<string, MarginRow> = {};
  // PRICE_TABLE entries — max payout across storage × condition matrix
  for (const [sku, storages] of Object.entries(effectivePriceTable)) {
    const label = SKU_LABELS[sku];
    if (!label) continue;
    let maxPayout = 0;
    for (const cond of Object.values(storages)) {
      for (const v of Object.values(cond)) {
        if (typeof v === "number" && v > maxPayout) maxPayout = v;
      }
    }
    if (maxPayout === 0) continue;
    const resell = getResellEstimate(label);
    out[sku] = makeRow(label, maxPayout, resell);
  }
  // BASE_PRICED entries — base is the max payout; override if set
  for (const [sku, m] of Object.entries(BASE_PRICED_MODELS)) {
    if (out[sku]) continue;
    if (m.inquiryOnly) continue;
    const payout = baseOverrides[sku] ?? m.base;
    if (!payout || payout <= 0) continue;
    const resell = getResellEstimate(m.label);
    out[sku] = makeRow(m.label, payout, resell);
  }
  return out;
}
function makeRow(label: string, payout: number, resell: number | null): MarginRow {
  if (resell == null) return { label, payout, resell: null, margin: null, marginPct: null };
  const margin = resell - payout;
  const marginPct = resell > 0 ? Math.round((margin / resell) * 100) : null;
  return { label, payout, resell, margin, marginPct };
}

export async function POST(req: NextRequest) {
  if (!checkAuth(req)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  let body: {
    priceTable?: OverridesShape["priceTable"];
    carrierDeductions?: OverridesShape["carrierDeductions"];
    baseOverrides?: OverridesShape["baseOverrides"];
    conditionAdj?: OverridesShape["conditionAdj"];
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Bad JSON" }, { status: 400 });
  }

  const current = await readOverrides();
  await snapshotToHistory(current);

  const merged: OverridesShape = {
    priceTable: deepMerge(current.priceTable, body.priceTable || {}),
    carrierDeductions: deepMerge(current.carrierDeductions, body.carrierDeductions || {}),
    baseOverrides: { ...current.baseOverrides, ...(body.baseOverrides || {}) },
    conditionAdj: deepMerge(current.conditionAdj, body.conditionAdj || {}),
    updatedAt: new Date().toISOString(),
  };

  await put(BLOB_KEY, JSON.stringify(merged, null, 2), {
    access: "public",
    contentType: "application/json",
    addRandomSuffix: false,
    allowOverwrite: true,
  });

  const overrideModels = Object.keys(merged.priceTable).length;
  const carrierOverrides = Object.keys(merged.carrierDeductions).length;
  return NextResponse.json({
    ok: true,
    overrideModels,
    carrierOverrides,
    updatedAt: merged.updatedAt,
  });
}

// DELETE supports three scopes:
//   no params       → clear ALL overrides (also snapshots first)
//   ?model=ip17p    → strip every override for one model
//   ?cell=ip17p/256/sealed → revert one specific cell
//   ?carrier=ip17p  → strip carrier deductions for one model
export async function DELETE(req: NextRequest) {
  if (!checkAuth(req)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const model = req.nextUrl.searchParams.get("model");
  const cell = req.nextUrl.searchParams.get("cell");
  const carrier = req.nextUrl.searchParams.get("carrier");
  const baseId = req.nextUrl.searchParams.get("base");
  const current = await readOverrides();
  await snapshotToHistory(current);

  let next: OverridesShape = current;
  let action = "clear-all";
  if (cell) {
    const [m, s, c] = cell.split("/");
    if (m && s && c && next.priceTable[m]?.[s]?.[c] !== undefined) {
      delete next.priceTable[m][s][c];
      if (Object.keys(next.priceTable[m][s]).length === 0) delete next.priceTable[m][s];
      if (Object.keys(next.priceTable[m]).length === 0) delete next.priceTable[m];
    }
    action = `clear-cell:${cell}`;
  } else if (carrier) {
    delete next.carrierDeductions[carrier];
    action = `clear-carrier:${carrier}`;
  } else if (baseId) {
    delete next.baseOverrides[baseId];
    action = `clear-base:${baseId}`;
  } else if (model) {
    delete next.priceTable[model];
    delete next.carrierDeductions[model];
    delete next.baseOverrides[model];
    delete next.conditionAdj[model];
    action = `clear-model:${model}`;
  } else {
    next = { priceTable: {}, carrierDeductions: {}, baseOverrides: {}, conditionAdj: {} };
  }
  next.updatedAt = new Date().toISOString();

  const empty =
    Object.keys(next.priceTable).length === 0 &&
    Object.keys(next.carrierDeductions).length === 0 &&
    Object.keys(next.baseOverrides).length === 0 &&
    Object.keys(next.conditionAdj).length === 0;
  if (empty) {
    try {
      const { blobs } = await list({ prefix: BLOB_KEY, limit: 5 });
      for (const b of blobs.filter((x) => x.pathname === BLOB_KEY)) {
        await del(b.url);
      }
    } catch {}
  } else {
    await put(BLOB_KEY, JSON.stringify(next, null, 2), {
      access: "public",
      contentType: "application/json",
      addRandomSuffix: false,
      allowOverwrite: true,
    });
  }

  return NextResponse.json({
    ok: true,
    action,
    overrideModels: Object.keys(next.priceTable).length,
    carrierOverrides: Object.keys(next.carrierDeductions).length,
  });
}
