#!/usr/bin/env python3
"""Generate a per-variant TABLET_SPECS const so getBrandExtras() can
show / hide / re-price each question based on what IWM actually asks
for that model.

For each page variant id we resolve which IWM submodel it maps to and
copy out: cellular_adj, stylus_adj, storage list. Apply IWM × 0.90 on
each adj so the page math doesn't need to discount.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
ADJ = json.loads((ROOT / "iwm-tablet-adjustments.json").read_text())
DISCOUNT = 0.10


def disc(v):
    return round(v * (1 - DISCOUNT))


# page variant id -> IWM key (must match apply-tablet-prices.py)
MAP = {
    # Samsung Galaxy Tab
    "stabs11u":   "samsung-tablet/galaxy-tab-s11-ultra",
    "stabs11":    "samsung-tablet/galaxy-tab-s11",
    "stabs9u":    "samsung-tablet/galaxy-tab-s9-ultra",
    "stabs9p":    "samsung-tablet/galaxy-tab-s9-plus",
    "stabs9":     "samsung-tablet/galaxy-tab-s9",
    "stabs9fep":  "samsung-tablet/galaxy-tab-s9-fe-plus",
    "stabs9fe":   "samsung-tablet/galaxy-tab-s9-fe",
    "stabs8u":    "samsung-tablet/galaxy-tab-s8-ultra",
    "stabs8p":    "samsung-tablet/galaxy-tab-s8-plus",
    "stabs8":     "samsung-tablet/galaxy-tab-s8",
    "stabs10u":   "samsung-tablet/galaxy-tab-s10-ultra",
    "stabs10p":   "samsung-tablet/galaxy-tab-s10-plus",
    "stabs10fep": "samsung-tablet/galaxy-tab-s10-fe-plus",
    "stabs10fe":  "samsung-tablet/galaxy-tab-s10-fe",
    "stabs10l":   "samsung-tablet/galaxy-tab-s10-lite",
    "stabs7p":    "samsung-tablet/galaxy-tab-s7-plus",
    "stabs7fe":   "samsung-tablet/galaxy-tab-s7-fe",
    "stabs7":     "samsung-tablet/galaxy-tab-s7",
    "stabs6l":    "samsung-tablet/galaxy-tab-s6-lite",
    "stabs6":     "samsung-tablet/galaxy-tab-s6",
    "stabs5e":    "samsung-tablet/galaxy-tab-s5e",
    "stabs4":     "samsung-tablet/galaxy-tab-s4-105",
    # OnePlus — only Pad Go 2 has cellular question
    "oppad3":     "oneplus-tablet/oneplus-pad-3",
    "oppadgo2":   "oneplus-tablet/oneplus-pad-go-2",
    "oppad2":     "oneplus-tablet/oneplus-pad-2",
    "oppad":      "oneplus-tablet/oneplus-pad",
    # Google
    "gpixeltab":  "google-tablet/google-pixel-tablet",
    # Lenovo
    "legtabg3":   "lenovo-tablet/lenovo-legion-tab-gen-3",
    # Microsoft Surface — only Pro 5/7/7+/8/10/11/Pro X have separate LTE question
    "surfpro11":     "microsoft-surface-pro/microsoft-surface-pro-11",
    "surfpro10biz":  "microsoft-surface-pro/microsoft-surface-pro-10",
    "surfpro9":      "microsoft-surface-pro/microsoft-surface-pro-9",
    "surfpro8":      "microsoft-surface-pro/microsoft-surface-pro-8",
    "surfpro7p":     "microsoft-surface-pro/microsoft-surface-pro-7-plus",
    "surfpro7":      "microsoft-surface-pro/microsoft-surface-pro-7",
    "surfpro6":      "microsoft-surface-pro/microsoft-surface-pro-6",
    "surfgo4":       "microsoft-surface-go/microsoft-surface-go-4",
    "surfgo3":       "microsoft-surface-go/microsoft-surface-go-3",
    "surfgo2":       "microsoft-surface-go/microsoft-surface-go-2",
    "surfprox2020":  "microsoft-surface-pro-x/microsoft-surface-pro-x",
    "surfprox2019":  "microsoft-surface-pro-x/microsoft-surface-pro-x",
}


def main():
    out_lines = ["// Per-variant tablet spec map — generated by scripts/gen-tablet-specs.py.",
                 "// Drives which questions getBrandExtras() shows for tablets, and the",
                 "// $ deltas it uses. Sourced from iwm-tablet-adjustments.json × 0.90.",
                 "// `cellularAdj` = how much MORE the cellular config pays vs Wi-Fi-only.",
                 "// `stylusAdj` = how much LESS we pay if the included stylus is missing.",
                 "// `storages` = the storage tiers IWM actually has for this model.",
                 "type TabletSpec = {",
                 "  cellularAdj?: number;   // omit if no cellular variant exists",
                 "  stylusAdj?: number;     // omit if the model has no stylus question",
                 "  storages?: string[];    // omit to show the global TABLET_STORAGE_OPTIONS",
                 "};",
                 "const TABLET_SPECS: Record<string, TabletSpec> = {"]
    for vid, adj_key in MAP.items():
        e = ADJ.get(adj_key, {})
        spec = {}
        conn = e.get("connectivity_adj") or {}
        if conn:
            # Find the "No / WiFi only" delta (negative number) — that's
            # how much LESS Wi-Fi gets. Cellular adj = absolute value of
            # the most-negative entry.
            no_vals = [v for k, v in conn.items() if "no" in k.lower() or "wifi only" in k.lower() or "wi-fi only" in k.lower()]
            if no_vals:
                cellular = abs(min(no_vals))
                if cellular > 0:
                    spec["cellularAdj"] = disc(cellular)
        styl = e.get("stylus_adj") or {}
        if styl:
            no_val = styl.get("no")
            if no_val is not None and no_val < 0:
                spec["stylusAdj"] = disc(no_val)  # already negative
        storages = list((e.get("storage_adj") or {}).keys())
        # Only emit storages list for plain GB labels (not Surface configs).
        plain = [s for s in storages if all(c.isdigit() or c.upper() in "GBTBLM " for c in s) and ("GB" in s or "TB" in s) and len(s) < 8]
        if plain and len(plain) == len(storages):
            spec["storages"] = sorted(plain, key=lambda s: 0 if s.startswith("64") else (1 if s.startswith("128") else (2 if s.startswith("256") else (3 if s.startswith("512") else 4))))
        if not spec:
            continue
        items = []
        if "cellularAdj" in spec: items.append(f'cellularAdj: {spec["cellularAdj"]}')
        if "stylusAdj" in spec: items.append(f'stylusAdj: {spec["stylusAdj"]}')
        if "storages" in spec: items.append(f'storages: {json.dumps(spec["storages"])}')
        out_lines.append(f'  {vid}: {{ {", ".join(items)} }},')
    out_lines.append("};")
    print("\n".join(out_lines))


if __name__ == "__main__":
    main()
